//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Deco.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class DecoLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		COMMAND=10, IDENTIFIER=11, NUMBER=12, WS=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"COMMAND", "IDENTIFIER", "NUMBER", "WS"
	};


	public DecoLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DecoLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'func'", "'('", "')'", "':'", "'{'", "'}'", "','", "';'", "'return'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "COMMAND", 
		"IDENTIFIER", "NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Deco.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DecoLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,13,86,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,0,1,0,
		1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,
		8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,5,9,59,8,9,10,9,12,9,62,9,9,1,9,
		1,9,1,9,1,9,1,10,1,10,5,10,70,8,10,10,10,12,10,73,9,10,1,11,4,11,76,8,
		11,11,11,12,11,77,1,12,4,12,81,8,12,11,12,12,12,82,1,12,1,12,1,60,0,13,
		1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,1,0,4,
		3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,122,1,0,48,57,3,0,9,10,
		13,13,32,32,89,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,
		0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,
		21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,1,27,1,0,0,0,3,32,1,0,0,0,5,34,1,
		0,0,0,7,36,1,0,0,0,9,38,1,0,0,0,11,40,1,0,0,0,13,42,1,0,0,0,15,44,1,0,
		0,0,17,46,1,0,0,0,19,53,1,0,0,0,21,67,1,0,0,0,23,75,1,0,0,0,25,80,1,0,
		0,0,27,28,5,102,0,0,28,29,5,117,0,0,29,30,5,110,0,0,30,31,5,99,0,0,31,
		2,1,0,0,0,32,33,5,40,0,0,33,4,1,0,0,0,34,35,5,41,0,0,35,6,1,0,0,0,36,37,
		5,58,0,0,37,8,1,0,0,0,38,39,5,123,0,0,39,10,1,0,0,0,40,41,5,125,0,0,41,
		12,1,0,0,0,42,43,5,44,0,0,43,14,1,0,0,0,44,45,5,59,0,0,45,16,1,0,0,0,46,
		47,5,114,0,0,47,48,5,101,0,0,48,49,5,116,0,0,49,50,5,117,0,0,50,51,5,114,
		0,0,51,52,5,110,0,0,52,18,1,0,0,0,53,54,5,34,0,0,54,55,5,34,0,0,55,56,
		5,34,0,0,56,60,1,0,0,0,57,59,9,0,0,0,58,57,1,0,0,0,59,62,1,0,0,0,60,61,
		1,0,0,0,60,58,1,0,0,0,61,63,1,0,0,0,62,60,1,0,0,0,63,64,5,34,0,0,64,65,
		5,34,0,0,65,66,5,34,0,0,66,20,1,0,0,0,67,71,7,0,0,0,68,70,7,1,0,0,69,68,
		1,0,0,0,70,73,1,0,0,0,71,69,1,0,0,0,71,72,1,0,0,0,72,22,1,0,0,0,73,71,
		1,0,0,0,74,76,7,2,0,0,75,74,1,0,0,0,76,77,1,0,0,0,77,75,1,0,0,0,77,78,
		1,0,0,0,78,24,1,0,0,0,79,81,7,3,0,0,80,79,1,0,0,0,81,82,1,0,0,0,82,80,
		1,0,0,0,82,83,1,0,0,0,83,84,1,0,0,0,84,85,6,12,0,0,85,26,1,0,0,0,5,0,60,
		71,77,82,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
