//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Deco.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DecoParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDecoListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] DecoParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] DecoParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] DecoParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] DecoParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] DecoParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] DecoParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] DecoParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] DecoParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] DecoParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] DecoParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDefinition([NotNull] DecoParser.VariableDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDefinition([NotNull] DecoParser.VariableDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] DecoParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] DecoParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DecoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] DecoParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DecoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] DecoParser.ExpressionContext context);
}
