//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Deco.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DecoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDecoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DecoParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] DecoParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] DecoParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] DecoParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] DecoParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DecoParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] DecoParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] DecoParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] DecoParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DecoParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DecoParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_expr([NotNull] DecoParser.Or_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expr([NotNull] DecoParser.And_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.eq_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEq_expr([NotNull] DecoParser.Eq_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.rel_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRel_expr([NotNull] DecoParser.Rel_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_expr([NotNull] DecoParser.Add_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.mul_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMul_expr([NotNull] DecoParser.Mul_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expr([NotNull] DecoParser.Unary_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] DecoParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDefinition([NotNull] DecoParser.VariableDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] DecoParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecoParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] DecoParser.AssignmentContext context);
}
