package com.adyingdeath.deco;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Compiler for generating Minecraft datapacks from Deco source files
 */
public class DatapackCompiler {
    private final String srcPath;
    private final String outputPath;
    
    // Default datapack format version (for pack.mcmeta)
    private static final int DEFAULT_PACK_FORMAT = 15; // for Minecraft 1.20.x
    private static final String DEFAULT_PACK_DESCRIPTION = "Generated by Deco Compiler";

    // File extension for Deco source files
    private static final String DECO_FILE_EXTENSION = ".deco";
    
    /**
     * Constructor for DatapackCompiler
     * 
     * @param srcPath The source folder with the same structure as a normal datapack
     * @param outputPath The output directory path for the generated datapack
     */
    public DatapackCompiler(String srcPath, String outputPath) {
        this.srcPath = srcPath;
        this.outputPath = outputPath;
    }
    
    /**
     * Compile the datapack
     * 
     * @return true if compilation was successful, false otherwise
     */
    public boolean compile() {
        try {
            // Read source datapack
            File dataDir = new File(this.srcPath, "data");
            File[] namespaceFiles = dataDir.listFiles();
            if (namespaceFiles == null) {
                System.out.println("There is nothing in the datapack. Compilation done.");
                return true;
            }

            // Get all the namespaces, and build a String array of their name.
            List<String> namespaces = Arrays.stream(namespaceFiles)
                    .filter((File::isDirectory))
                    .map(File::getName)
                    .toList();

            System.out.println("Done");
            // Create datapack directory structure
            if (!createDatapackStructure()) {
                return false;
            }

            // Find all Deco files recursively
            List<File> decoFiles = findDecoFiles(new File(srcPath));

            if (decoFiles.isEmpty()) {
                System.err.println("Warning: No .deco files found in " + srcPath);
                return false;
            }

            // Compile each Deco file
            int successCount = 0;
            int failureCount = 0;

            for (File decoFile : decoFiles) {
                String relativePath = getRelativePath(new File(srcPath), decoFile);

                try {
                    boolean success = compileDecoFile(decoFile, relativePath);
                    if (success) {
                        successCount++;
                    } else {
                        failureCount++;
                    }
                } catch (Exception e) {
                    failureCount++;
                    System.err.println("Error compiling " + relativePath + ": " + e.getMessage());
                }
            }

            // Print summary
            System.out.println("Datapack compilation complete. Summary:");
            System.out.println("  Total files: " + decoFiles.size());
            System.out.println("  Successful: " + successCount);
            System.out.println("  Failed: " + failureCount);

            return failureCount == 0;

        } catch (Exception e) {
            System.err.println("Error during datapack compilation: " + e.getMessage());
            return false;
        }
    }
    
    /**
     * Create the datapack directory structure
     * 
     * @return true if successful, false otherwise
     */
    private boolean createDatapackStructure() {
        try {
            // Create base directories
            File outputDir = new File(outputPath);
            // [datapack]/data
            File dataDir = new File(outputPath, "data");
            // [datapack]/data/minecraft
            File minecraftDir = new File(dataDir, "minecraft");

            File functionsDir = new File(minecraftDir, "functions");
            File tagsDir = new File(minecraftDir, "tags");
            File functionTagsDir = new File(tagsDir, "functions");
            
            // Create directories
            createDirectory(outputDir);
            createDirectory(dataDir);
            createDirectory(minecraftDir);
            createDirectory(functionsDir);
            createDirectory(tagsDir);
            createDirectory(functionTagsDir);
            
            return true;
        } catch (Exception e) {
            System.err.println("Error creating datapack structure: " + e.getMessage());
            return false;
        }
    }
    
    /**
     * Create a directory if it doesn't exist
     * 
     * @param dir Directory to create
     */
    private void createDirectory(File dir) throws IOException {
        if (!dir.exists()) {
            if (!dir.mkdirs()) {
                throw new IOException("Failed to create directory: " + dir.getPath());
            }
        }
    }
    
    /**
     * Find all Deco files in a directory recursively
     * 
     * @param dir Directory to search
     * @return List of Deco files
     */
    private List<File> findDecoFiles(File dir) {
        List<File> decoFiles = new ArrayList<>();
        File[] files = dir.listFiles();
        
        if (files == null) {
            return decoFiles;
        }
        
        for (File file : files) {
            if (file.isDirectory()) {
                decoFiles.addAll(findDecoFiles(file));
            } else if (file.getName().endsWith(DECO_FILE_EXTENSION)) {
                decoFiles.add(file);
            }
        }
        
        return decoFiles;
    }
    
    /**
     * Get the relative path of a file from a base directory
     * 
     * @param baseDir Base directory
     * @param file File
     * @return Relative path
     */
    private String getRelativePath(File baseDir, File file) {
        String basePath = baseDir.getAbsolutePath();
        String filePath = file.getAbsolutePath();
        
        if (filePath.startsWith(basePath)) {
            return filePath.substring(basePath.length() + 1);
        }
        
        return file.getPath();
    }
    
    /**
     * Compile a Deco file
     * 
     * @param decoFile Deco source file
     * @param relativePath Relative path of the file
     * @return true if compilation was successful, false otherwise
     */
    private boolean compileDecoFile(File decoFile, String relativePath) {
        try {
            // Calculate output file paths based on relative path
            String namespacePath = getNamespacePath(relativePath);
            
            // Create compiler instance
            Compiler compiler = new Compiler(false);
            
            // Calculate output file path for Minecraft function
            String mcFunctionOutputPath = Paths.get(
                outputPath, 
                "data", 
                namespacePath
            ).toString();
            
            // Ensure output directory exists
            File outputDir = new File(mcFunctionOutputPath).getParentFile();
            if (!outputDir.exists() && !outputDir.mkdirs()) {
                System.err.println("Failed to create output directory: " + outputDir.getPath());
                return false;
            }
            
            // Compile the file
            boolean result = compiler.compile(decoFile.getAbsolutePath(), mcFunctionOutputPath);
            
            if (result) {
                return true;
            } else {
                System.err.println("Failed to compile: " + relativePath);
                return false;
            }
        } catch (Exception e) {
            System.err.println("Error compiling " + relativePath + ": " + e.getMessage());
            return false;
        }
    }
    
    /**
     * Get the namespace path from a relative path
     * Converts a file path like "namespace/functions/test.deco" to "namespace/functions/test"
     * 
     * @param relativePath Relative path
     * @return Namespace path
     */
    private String getNamespacePath(String relativePath) {
        // Remove file extension
        String path = relativePath;
        if (path.endsWith(DECO_FILE_EXTENSION)) {
            path = path.substring(0, path.length() - DECO_FILE_EXTENSION.length());
        }
        
        // Handle path separators for different OS
        path = path.replace('\\', '/');
        
        return path;
    }
}